<a href="https://colab.research.google.com/github/LavanyaMuthuraman/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

The first thing we want to do is import numpy.

In [1]:
import numpy as np

In [8]:
# Let us first define a Python list containing the ages of 10 people

ages_list = [12, 78, 89 , 56 , 24 , 68 , 92, 65, 43, 67]
print(ages_list)

[12, 78, 89, 56, 24, 68, 92, 65, 43, 67]


In [19]:
# Let us first define a Python list containing the ages of 10 people

ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[12 78 89 56 24 68 92 65 43 67]


In [11]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[12 78 89 56 24 68 92 65 43 67]
Size:	 10
Shape:	 (10,)


In [12]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


## Multi-Dim

In [14]:
# Now let us define a new list containing the weights of these 10 people.

weight_list = [72, 28, 65, 36, 56, 16, 56, 78, 75, 72]

In [15]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[12 78 89 56 24 68 92 65 43 67]
 [72 28 65 36 56 16 56 78 75 72]]
Size:	 20
Shape:	 (2, 10)


In [18]:
# 1 X 20 = 4 X 5 = 5 X 4 = 20 X 1  

people = people.reshape(20,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[12]
 [78]
 [89]
 [56]
 [24]
 [68]
 [92]
 [65]
 [43]
 [67]
 [72]
 [28]
 [65]
 [36]
 [56]
 [16]
 [56]
 [78]
 [75]
 [72]]
Size:	 20
Shape:	 (20, 1)


## Exercise

In [26]:
import numpy as np

In [34]:
one_dim = [7, 9, 65, 33, 85, 99,67, 56, 78]
print(one_dim)

[7, 9, 65, 33, 85, 99, 67, 56, 78]


In [35]:
list1 = np.array(one_dim)
print(type(list1))
print(list1)

<class 'numpy.ndarray'>
[ 7  9 65 33 85 99 67 56 78]


In [36]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


In [45]:
# Now let us define a new list containing the weights of these 10 people.

mat=np.array([[1,2,4],[2,3,0],[0,5,1]])

In [46]:
mat.reshape(1,9) 
# changed the shape of above array to 1 x 9

array([[1, 2, 4, 2, 3, 0, 0, 5, 1]])

In [40]:
# 1 X 18 = 9 X 2 =  6 X 3 = 3 X 6 = 2 X 9 = 18 X 1  

people = people.reshape(18,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[ 7]
 [ 9]
 [65]
 [33]
 [85]
 [99]
 [67]
 [56]
 [78]
 [ 1]
 [ 2]
 [ 4]
 [ 2]
 [ 3]
 [ 0]
 [ 0]
 [ 5]
 [ 1]]
Size:	 18
Shape:	 (18, 1)


## Array Generation

In [47]:
# Instead of defining an array manually, we can ask numpy to do it for us.
# The np.arange() method creates a range of numbers with user defined steps between each.

In [57]:
five_times_table=np.arange(0,55,5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [52]:
# The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.
five_spaced=np.linspace(0,50,11) 
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [56]:
# The .repeat() method will repeat an object you pas a specified number of times.
twoArr=np.repeat(2,10)
twoArr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [55]:
# The np.eye() functions will create an identity matrix/array for us.
identity_matrix=np.eye(6)
identity_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Operations

In [ ]:
# There are many, many operations which we can perform on arrays. Below, we demonstrate a few.

In [58]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [59]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


## Speed Test

In [60]:
# If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [61]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [62]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [63]:
%timeit five_times_table_lge + 5

1.23 µs ± 11.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [64]:
%timeit [e + 5 for e in fives_list]

59.6 µs ± 508 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [65]:
# Boolean string operations can also be performed on ndarrays.
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

## TRANSPOSE

In [91]:
people.shape = (2, 9)
print(people, "\n")
print(people.T)

[[ 7  9 65 33 85 99 67 56 78]
 [ 1  2  4  2  3  0  0  5  1]] 

[[ 7  1]
 [ 9  2]
 [65  4]
 [33  2]
 [85  3]
 [99  0]
 [67  0]
 [56  5]
 [78  1]]


## Data Types

In [67]:
# As previously mentioned, ndarrays can only have one data type.
# If we want to obtain or change this, we use the .dtype attribute.

In [70]:
people.dtype

dtype('int64')

In [71]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [72]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [73]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [74]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [75]:
ages_with_strings.size

126

In [76]:
ages_with_strings.size/21

6.0

In [77]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [78]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


## Exercise

In [79]:
#### Create an array of string numbers, but use dtype to make it an array of floats.

import numpy as np
X= ["3.4", "2.5", "6.2"]
Y = np.asarray(X, dtype=float)

print(X, type(X), type(X[0]))
print(Y, type(Y), type(Y[0]))

['3.4', '2.5', '6.2'] <class 'list'> <class 'str'>
[3.4 2.5 6.2] <class 'numpy.ndarray'> <class 'numpy.float64'>


In [80]:
#### Transpose the matrix, printing the new size and shape.
import numpy 
matrix=[[11,21,32],[41,53,64]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[11, 21, 32], [41, 53, 64]]


[[11 41]
 [21 53]
 [32 64]]


In [81]:
print(type(matrix))

<class 'list'>


In [82]:
numpy.array(matrix, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

## Array Slicing Operations

In [ ]:
# As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [84]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [85]:
five_times_table[0]

0

In [86]:
five_times_table[-1]

50

In [89]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [87]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [ ]:
# We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [92]:
print(people)
people[:3, :3]

[[ 7  9 65 33 85 99 67 56 78]
 [ 1  2  4  2  3  0  0  5  1]]


array([[ 7,  9, 65],
       [ 1,  2,  4]])

## Exercise

Create a numpy array with 50 zeros
Create a np array of 2 repeated 20 times
Create a numpy array from 0 to 2 pi in steps of 0.1
For one of the arrays generated:

Get the first five values

Get the last 3 values

Get the 4th value to the 7th value 

In [93]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
np.repeat(2, 20)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [95]:
x = np.arange(start=0, stop=2*3.14, step=0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [96]:
x[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [97]:
x[60:]

array([6. , 6.1, 6.2])

In [98]:
x[4:7]

array([0.4, 0.5, 0.6])

In [99]:
# We can reverse an array by using .flip() or by using the :: operator.
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [100]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [101]:
# We can also use the :: operator to select steps of the original array.
five_times_table[0::3] #Every 3rd element starting from 0

array([ 0, 15, 30, 45])

## Exercise

take one of the arrays you defined and

(*)#### Reverse it

(*)#### Only keep every 4th element.

(*)#### Get every 2nd element, starting from the last and moving backwards.

In [102]:
result = np.flip(x)

print("Reverse array",(result))

Reverse array [6.2 6.1 6.  5.9 5.8 5.7 5.6 5.5 5.4 5.3 5.2 5.1 5.  4.9 4.8 4.7 4.6 4.5
 4.4 4.3 4.2 4.1 4.  3.9 3.8 3.7 3.6 3.5 3.4 3.3 3.2 3.1 3.  2.9 2.8 2.7
 2.6 2.5 2.4 2.3 2.2 2.1 2.  1.9 1.8 1.7 1.6 1.5 1.4 1.3 1.2 1.1 1.  0.9
 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0. ]


In [ ]:
x[4]

In [103]:
a = [2, 4, 6, 8, 10]
b = [2, 4, 6, 8, 10]
print( a[::2][::-1])
print (b[::2][::-1])

[10, 6, 2]
[10, 6, 2]


## Stats

In [104]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [105]:
nums = np.arange(0, 4, 0.2555)

## Exercise

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [106]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


## Random

In [107]:
# With np.random, we can generate a number of types of dataset, and create training data.

# The below code simulates a fair coin toss.

In [108]:
flip = np.random.choice([0,1], 10)
flip

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [109]:
np.random.rand(10,20,9)

array([[[0.26568084, 0.46895221, 0.21911703, ..., 0.09356945,
         0.34862596, 0.3564297 ],
        [0.39598529, 0.66767985, 0.04623052, ..., 0.2701614 ,
         0.69019296, 0.16740348],
        [0.53864892, 0.52073032, 0.68401376, ..., 0.98938029,
         0.12960524, 0.56065052],
        ...,
        [0.35022381, 0.16558602, 0.69404249, ..., 0.69537364,
         0.89965442, 0.24448627],
        [0.18331089, 0.63889982, 0.96177671, ..., 0.1454486 ,
         0.0802867 , 0.39406036],
        [0.07377851, 0.80610264, 0.10943839, ..., 0.44755664,
         0.47598339, 0.17962455]],

       [[0.75832596, 0.53820113, 0.23681477, ..., 0.05117605,
         0.94608186, 0.09332065],
        [0.51899204, 0.78741206, 0.84733397, ..., 0.87347877,
         0.15842341, 0.47459206],
        [0.32384525, 0.11836036, 0.33235181, ..., 0.56815124,
         0.44907512, 0.20274331],
        ...,
        [0.26335229, 0.66609199, 0.802977  , ..., 0.90142727,
         0.63825321, 0.51185314],
        [0.1

In [110]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

## Exercise

Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [111]:
flip_for_die = np.random.choice([1,2,3,4,5,6], 10)
flip_for_die

array([4, 1, 2, 1, 1, 3, 3, 6, 3, 1])

In [112]:
coin=np.random.choice(['Head','Head','Tail'],10)

In [113]:
coin

array(['Head', 'Head', 'Head', 'Head', 'Head', 'Tail', 'Head', 'Head',
       'Head', 'Tail'], dtype='<U4')